# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.0
