# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.35.5
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.34.8
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.33.12
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.32.11
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.31.14
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.30.13
