# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.34.3
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.33.4
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.32.8
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.31.12
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.30.13
