checks:
  exclude:
    # TODO: exclude no rule
    # https://github.com/Kong/charts/issues/753
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
