# renovate: datasource=github-releases depName=stackrox/kube-linter
kube-linter: "0.7.6"
# renovate: datasource=github-releases depName=jlandowner/helm-chartsnap
chartsnap: "0.6.0"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.11.0"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.8"
