# The minimum values.yaml configuration necessary for Kong without the ingress controller, using the Postgres subchart
image:
  repository: kong
  tag: "2.0"

env:
  prefix: /kong_prefix/
  database: postgres

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlDatabase: kong
  service:
    port: 5432

ingressController:
  enabled: false
  installCRDs: false
