# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong
  tag: "2.3"

env:
  prefix: /kong_prefix/
  database: "off"

ingressController:
  enabled: true
  installCRDs: false

deployment:
  initContainers:
  - name: "bash"
    image: "bash:latest"
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      request:
        cpu: "100m"
        memory: "64Mi"
    volumeMounts:
    - name: "tmpDir"
      mountPath: "/opt/tmp"
  userDefinedVolumes:
  - name: "tmpDir"
    emptyDir: {}
  userDefinedVolumeMounts:
  - name: "tmpDir"
    mountPath: "/opt/tmp"

