deployment:
  kong:
    enabled: false

proxy:
  ## This must match the gateway release's proxy Service name.
  ## The Service name uses the pattern "<release name>-kong-proxy".
  ## In this example, the companion gateway release is named "gw"
  nameOverride: gw-kong-proxy

ingressController:
  enabled: true
  ## This example creates a static 2-Pod Kong Igress Controller deployment
  ## With service discovery enabled leader election will be enabled and only one
  ## instance will ever talk to the accompanying Gateways.
  replicaCount: 2
  serviceDiscovery:
    enabled: true
    adminApiService:
      ## This must match the gateway release's admin Service name.
      ## The Service name uses the pattern "<release name>-kong-admin".
      ## In this example, the companion gateway release is named "gw"
      name: gw-kong-admin
