
# install chart with a service account
deployment:
  serviceAccount:
    create: true
    name: "my-kong-sa"
    annotations: {}

ingressController:
  serviceAccount:
    create: false
  deployment:
    pod:
      container:
        env:
          anonymous_reports: "false"
