image:
  repository: docker.io/kong/nightly-gateway-operator-oss
  tag: "20250130"
  effectiveSemver: "1.5.0"

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 1
  periodSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "false"
