image:
  repository: gcr.io/formidable-app-197923/kong-brain-immunity
  tag: 1.2.1
  pullPolicy: IfNotPresent
  # repository: kong-docker-kong-brain-internal-builds.bintray.io/kong-brain
  # tag: master

imagePullSecrets: {}

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

kongAdmin:
  # Set this to the Kong Admin API hostname
  host: skulking-moose.admin.forever.blue
  # Set this to the Kong Admin API port
  servicePort: 443
  # Set this to the Kong Admin API protocol
  protocol: https
  # Set this to the Kong Admin API token
  token: my-token

collector:
  containerPort: 5000
  # Set a nodePort which is available
  nodePort: 31555
  service:
    type: NodePort
    port: 5000

postgresql:
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432

redis:
  enabled: true
  port: 6379
  password: redis

ingress:
  enabled: false

# Enable this for running integration tests
testendpoints:
  enabled: true
