{{- /* Due to GKE versions (e.g. v1.23.15-gke.1900) we need to handle pre-release part of the version as well.
See the related documentation of semver module that Helm depends on for semverCompare:
https://github.com/Masterminds/semver#working-with-prerelease-versions
Related Helm issue: https://github.com/helm/helm/issues/3810 */}}

{{- if (and (or .Values.deployment.serviceAccount.name .Values.deployment.serviceAccount.create) (semverCompare "<1.20.0-0" .Capabilities.KubeVersion.Version))  -}}
---
{{ $proxySA := dict -}}
{{- $_ = set $proxySA "namespace" (include "kong.namespace" .) -}}
{{- $_ = set $proxySA "defaultName" (printf "%s-%s" (include "kong.fullname" .) "proxy") -}}
{{- template "kong.serviceAccountTokenSecret" (mustMerge .Values.deployment.serviceAccount $proxySA) -}}
{{- end -}}

{{- if (and (or .Values.ingressController.serviceAccount.name .Values.ingressController.serviceAccount.create) (semverCompare "<1.20.0-0" .Capabilities.KubeVersion.Version))  -}}
---
{{ $controllerSA := dict -}}
{{- $_ = set $controllerSA "namespace" (include "kong.namespace" .) -}}
{{- $_ = set $controllerSA "defaultName" (printf "%s-%s" (include "kong.fullname" .) "controller") -}}
{{- template "kong.serviceAccountTokenSecret" (mustMerge .Values.ingressController.serviceAccount $controllerSA) -}}
{{- end -}}

{{- define "kong.serviceAccountTokenSecret" -}}
{{- if and (or .Values.deployment.serviceAccount.create .Values.deployment.serviceAccount.name) (semverCompare "<1.20.0-0" .Capabilities.KubeVersion.Version) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kong.serviceAccountTokenName" . }} 
  namespace: {{ .namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "kong.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end -}}
{{- end -}}
