ko-crds:
  enabled: false

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 1
  periodSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  # gateway controller
  enable_controller_gateway: true

enableControlplaneConfigDump: true
