tolerations:
- key: "example-key"
  operator: "Exists"
  effect: "NoSchedule"

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 1
  periodSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "false"
