apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kgo
  name: {{ template "kong.fullname" . }}
  namespace:  {{ template "kong.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: kgo
