apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ template "kong.fullname" . }}
  namespace:  {{ template "kong.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
