{{- if and (.Values.ingressController.konnect.license.enabled) (semverCompare ">= 3.5.0" (include "kong.effectiveVersion" .Values.ingressController.image)) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "kong.namespace" . }}
  name: konnect-license-{{ template "kong.ingress.konnect.controlPlaneID" . }}
{{- end }}