{{- if and .Values.deployment.kong.enabled .Values.deployment.serviceAccount.create }}
---
{{ $proxySA := dict -}}
{{- $_ := set $proxySA "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $proxySA "defaultName" (printf "%s-%s" (include "kong.fullname" .) "proxy") -}}
{{- $_ := set $proxySA "labels" (include "kong.metaLabels" .) -}}
{{- template "kong.serviceAccount" (mustMerge .Values.deployment.serviceAccount $proxySA) -}}
{{- end -}}

{{- if and .Values.ingressController.deployment.enabled .Values.ingressController.serviceAccount.create }}
---
{{ $controllerSA := dict -}}
{{- $_ := set $controllerSA "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $controllerSA "defaultName" (printf "%s-%s" (include "kong.fullname" .) "controller") -}}
{{- $_ := set $controllerSA "labels" (include "kong.metaLabels" .) -}}
{{- template "kong.serviceAccount" (mustMerge .Values.ingressController.serviceAccount $controllerSA) -}}
{{- end -}}

{{- define "kong.serviceAccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kong.serviceAccountName" . }}
  namespace: {{ .namespace }}
  {{- if .annotations }}
  annotations:
  {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- .labels | nindent 4 }}
{{- end -}}

{{/*
Create the name of the service account to use
*/}}
{{- define "kong.serviceAccountName" -}}
{{- if .create -}}
    {{ default .defaultName .name }}
{{- else -}}
    {{ default "default" .name }}
{{- end -}}
{{- end -}}

{{- define "kong.serviceAccountName.controller" -}}
{{ template "kong.serviceAccountName" (mustMerge .Values.ingressController.serviceAccount (dict "defaultName" (printf "%s-%s" (include "kong.fullname" .) "controller"))) }}
{{- end -}}

{{- define "kong.serviceAccountName.proxy" -}}
{{ template "kong.serviceAccountName" (mustMerge .Values.deployment.serviceAccount (dict "defaultName" (printf "%s-%s" (include "kong.fullname" .) "proxy"))) }}
{{- end -}}

{{/*
Create the name of the secret for service account token to use
*/}}
{{- define "kong.serviceAccountTokenName" -}}
{{ include "kong.serviceAccountName" . }}-token
{{- end -}}

{{- define "kong.serviceAccountTokenName.controller" -}}
{{ template "kong.serviceAccountTokenName" (mustMerge .Values.ingressController.serviceAccount (dict "defaultName" (printf "%s-%s" (include "kong.fullname" .) "controller"))) }}
{{- end -}}

{{- define "kong.serviceAccountTokenName.proxy" -}}
{{ template "kong.serviceAccountTokenName" (mustMerge .Values.deployment.serviceAccount (dict "defaultName" (printf "%s-%s" (include "kong.fullname" .) "proxy"))) }}
{{- end -}}
