{{- if and (or .Values.deployment.kong.enabled .Values.deployment.controller.enabled) .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kong.serviceAccountName" . }}
  namespace: {{ template "kong.namespace" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
{{- end -}}
