apiVersion: v2
description: Kong AI Gateway data plane, connecting to a Konnect AI Gateway control plane
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: kong-ai-gateway
sources:
  - https://github.com/Kong/charts/tree/main/charts/kong-ai-gateway
version: 0.2.0
appVersion: "2.0.3"
