ingressController:
  enabled: true
  admissionWebhook:
    enabled: true
    filterSecrets: false
    objectSelector:
      matchLabels:
        app.kubernetes.io/instance: kong-custom
      matchExpressions:
      - key: environment
        operator: In
        values:
        - production
