ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.6.0.0"

enterprise:
  enabled: true
  rbac:
    enabled: true
    admin_gui_auth: openid-connect
    admin_gui_auth_conf_secret: openid-connect-secret

readinessProbe:
  httpGet:
    path: "/status"
    port: status
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1
