ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.6.0.0"

enterprise:
  enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    session_conf_secret: session-conf-secret

readinessProbe:
  httpGet:
    path: "/status"
    port: status
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1
