env:
  anonymous_reports: "off"
ingressController:
  env:
    anonymous_reports: "false"
  image:
    tag: "3.1"

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1
