# This tests the following unrelated aspects of Ingress Controller
# - ingressController deploys with a database
# - TODO database-backed proxy works _without_ stream listens
#   This test is a duplicate of test2-values.yaml to handle the https://github.com/Kong/charts/issues/295
#   workaround when the socket file is _not_ created
ingressController:
  enabled: true
  installCRDs: false
  env:
    anonymous_reports: "false"
postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlDatabase: kong
  service:
    port: 5432
env:
  anonymous_reports: "off"
  database: "postgres"
# - ingress resources are created without hosts
admin:
  type: NodePort
  ingress:
    enabled: true
    hosts: []
    path: /
proxy:
  type: NodePort
  ingress:
    enabled: true
    hostname: proxy.kong.example
    annotations: {}
    path: /

# - PDB is enabled
podDisruptionBudget:
  enabled: true
# update strategy
updateStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
