# CI test for testing dbless deployment without ingress controllers
# - disable ingress controller
# - no static config
ingressController:
  enabled: false
# - disable DB for kong
env:
  anonymous_reports: "off"
  database: "off"
postgresql:
  enabled: false
proxy:
  type: NodePort
deployment:
  initContainers:
    - name: "bash"
      image: "bash:latest"
      command: ["/bin/sh", "-c", "true"]
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
      volumeMounts:
      - name: "tmpdir"
        mountPath: "/opt/tmp"
  userDefinedVolumes:
  - name: "tmpdir"
    emptyDir: {}
  userDefinedVolumeMounts:
  - name: "tmpdir"
    mountPath: "/opt/tmp"
