ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.4"

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  httpGet:
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "off"
