{{- if .Values.deployment.kong.enabled }}
{{- $deployConfig := dict -}}
{{- $deployConfig = (mustMerge $deployConfig .deployment.kong) -}}
{{- $deployPreRender := dict -}} {{/* collection of values rendered from includes, so that there's no risk of colliding with things from the merge */}}
{{- $podConfig := dict -}}
{{- $_ := set $deployPreRender "name" (printf "%s-%s (include "kong.fullname" .) "proxy") -}}
{{- $_ := set $deployPreRender "namespace" (include "kong.namespace" .) -}}
# TODO 921 combine with .deployment.controller.labels.
# unsure how the types work out here--kong.metaLabels produces YAML output, and I'm not sure if we can
# just concat them as strings or what. can maybe ignore .deployment.controller.labels--it wasn't
# included in the past and we instead set extraLabels on EVERYTHING. that's apparently sufficient for
# user needs (there's been no request to provide separate per-resource labels here), but incongruous
# with how we handle annotations
{{- $_ := set $deployPreRender "labels" (include "kong.metaLabels" .) -}}
# TODO 921 this needs changes to the helper template since we'll need to point to two different sets of pods.
# in ingress chart this is relying on different fullnames. can't simply format since there multiple keys,
# need to pass a suffix to the helper
{{- $_ := set $deployPreRender "selectorMatchLabels" (include "kong.selectorLabels" .) -}}
{{- $_ := set $deployPreRender "serviceAccountTokenName" (template "kong.serviceAccountTokenName" .) -}}

{{/*
# TODO 921 unsure if we want to keep this gate. it's probably simpler to just say "don't set .Values.dblessConfig.config
# if you're not using a setup that makes sense for it"
{{- if (and (not .Values.ingressController.enabled) (eq .Values.env.database "off" )) }}
*/}}
{{- if .Values.dblessConfig.config }}
{{- $- := set $deployPreRender "dblessChecksum" (toYaml .Values.dblessConfig.config | sha256sum) }}
{{- end }}
{{/* # TODO 921 end of the old gate above
{{- end }}
*/}}

{{- $preRender := dict -}}
{{- $_ := set $preRender "deployment" $deployPreRender -}}
{{- $_ := set $preRender "pod" $podPreRender -}}
{{- $_ := set $deployConfig "pre" $preRender -}} # TODO 921 maybe think of a better key name
