name: README.md gh-pages sync
concurrency:
  group: readme-gh-pages-sync
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: gh-pages

      - name: Sync README.md to gh-pages
        run: |
          git config user.name "Kong's Team k8s bot"
          git config user.email "team-k8s+github-bot@konghq.com"
          git checkout main -- README.md
          git commit -m "chore: sync README.md from main branch" || echo "No changes to commit"
          git push origin gh-pages
